// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vaper_Api.Models;

#nullable disable

namespace Vaper_Api.Migrations
{
    [DbContext(typeof(VaperContext))]
    [Migration("20251211131117_AddImagenesEnCategoriaYProducto")]
    partial class AddImagenesEnCategoriaYProducto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vaper_Api.Models.Abono", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("Monto")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("SaldoRestante")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("VentaPedidoId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Abonos__3214EC078D852302");

                    b.HasIndex("VentaPedidoId");

                    b.ToTable("Abonos");
                });

            modelBuilder.Entity("Vaper_Api.Models.CategoriaProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<int?>("IdImagen")
                        .HasColumnType("int");

                    b.Property<string>("NombreCategoria")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC079C3563B3");

                    b.HasIndex("IdImagen");

                    b.ToTable("Categoria_Productos");
                });

            modelBuilder.Entity("Vaper_Api.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NumeroCompra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Compras__3214EC07838F141B");

                    b.HasIndex("Estado");

                    b.HasIndex("ProveedorId");

                    b.HasIndex(new[] { "NumeroCompra" }, "UQ__Compras__5F9B8DECF727A666")
                        .IsUnique();

                    b.ToTable("Compras");
                });

            modelBuilder.Entity("Vaper_Api.Models.Cotizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Cotizaci__3214EC07");

                    b.ToTable("Cotizaciones");
                });

            modelBuilder.Entity("Vaper_Api.Models.DetalleCompra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("CompraId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Detalle___3214EC070BE39BA9");

                    b.HasIndex("CompraId");

                    b.HasIndex("ProductoId");

                    b.ToTable("Detalle_Compras");
                });

            modelBuilder.Entity("Vaper_Api.Models.DetalleCotizacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CotizacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Detalle___3214EC07");

                    b.HasIndex("CotizacionId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetalleCotizaciones");
                });

            modelBuilder.Entity("Vaper_Api.Models.DetalleDevolucione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int?>("DevolucionId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("VentaPedidoId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Detalle___3214EC0737C9A04E");

                    b.HasIndex("DevolucionId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VentaPedidoId");

                    b.ToTable("Detalle_Devoluciones");
                });

            modelBuilder.Entity("Vaper_Api.Models.DetalleVentaPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("VentaPedidoId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Detalle___3214EC073A97D16E");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaPedidoId");

                    b.ToTable("Detalle_Venta_Pedidos");
                });

            modelBuilder.Entity("Vaper_Api.Models.Devolucione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id")
                        .HasName("PK__Devoluci__3214EC074BBF49D5");

                    b.ToTable("Devoluciones");
                });

            modelBuilder.Entity("Vaper_Api.Models.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreEstado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Estados__3214EC07AE4F961E");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("Vaper_Api.Models.Imagene", b =>
                {
                    b.Property<int>("IdImagen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdImagen"));

                    b.Property<int?>("ProductoId")
                        .HasColumnType("int");

                    b.Property<string>("Urlimagen")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("URLImagen");

                    b.HasKey("IdImagen")
                        .HasName("PK__Imagenes__B42D8F2A5DFCE52B");

                    b.HasIndex("ProductoId");

                    b.ToTable("Imagenes");
                });

            modelBuilder.Entity("Vaper_Api.Models.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombrePermiso")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Permisos__3214EC0717827BAC");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("Vaper_Api.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<int?>("IdImagen")
                        .HasColumnType("int");

                    b.Property<string>("NombreProducto")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Producto__3214EC07320121CE");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Vaper_Api.Models.Proveedore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("NombreCompletoORazonSocial")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NombreCompleto_o_RazonSocial");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("RepresentanteLegal")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Proveedo__3214EC0773176097");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("Vaper_Api.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("EstadoRol")
                        .HasColumnType("bit");

                    b.Property<string>("NombreRol")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC07727368DD");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Vaper_Api.Models.RolesPermiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PermisoId")
                        .HasColumnType("int");

                    b.Property<int?>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Roles_Pe__3214EC07223D2819");

                    b.HasIndex("PermisoId");

                    b.HasIndex("RolId");

                    b.ToTable("Roles_Permisos");
                });

            modelBuilder.Entity("Vaper_Api.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Barrio")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Contraseña")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<bool?>("EstadoUsuario")
                        .HasColumnType("bit");

                    b.Property<DateOnly?>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombres")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<int?>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id")
                        .HasName("PK__Usuarios__3214EC0728542FB5");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Vaper_Api.Models.VentaPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CiudadEntrega")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DepartamentoEntrega")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DireccionEntrega")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Envio")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime");

                    b.Property<string>("MetodoPago")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Venta_Pe__3214EC073FC94792");

                    b.HasIndex("EstadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Venta_Pedidos");
                });

            modelBuilder.Entity("Vaper_Api.Models.Abono", b =>
                {
                    b.HasOne("Vaper_Api.Models.VentaPedido", "VentaPedido")
                        .WithMany("Abonos")
                        .HasForeignKey("VentaPedidoId")
                        .HasConstraintName("FK__Abonos__VentaPed__0D7A0286");

                    b.Navigation("VentaPedido");
                });

            modelBuilder.Entity("Vaper_Api.Models.CategoriaProducto", b =>
                {
                    b.HasOne("Vaper_Api.Models.Imagene", "Imagen")
                        .WithMany("Categorias")
                        .HasForeignKey("IdImagen");

                    b.Navigation("Imagen");
                });

            modelBuilder.Entity("Vaper_Api.Models.Compra", b =>
                {
                    b.HasOne("Vaper_Api.Models.Estado", "EstadoNavigation")
                        .WithMany("Compras")
                        .HasForeignKey("Estado")
                        .HasConstraintName("FK__Compras__Estado__17036CC0");

                    b.HasOne("Vaper_Api.Models.Proveedore", "Proveedor")
                        .WithMany("Compras")
                        .HasForeignKey("ProveedorId")
                        .HasConstraintName("FK__Compras__Proveed__160F4887");

                    b.Navigation("EstadoNavigation");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Vaper_Api.Models.DetalleCompra", b =>
                {
                    b.HasOne("Vaper_Api.Models.Compra", "Compra")
                        .WithMany("DetalleCompras")
                        .HasForeignKey("CompraId")
                        .HasConstraintName("FK__Detalle_C__Compr__19DFD96B");

                    b.HasOne("Vaper_Api.Models.Producto", "Producto")
                        .WithMany("DetalleCompras")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("FK__Detalle_C__Produ__1AD3FDA4");

                    b.Navigation("Compra");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Vaper_Api.Models.DetalleCotizacion", b =>
                {
                    b.HasOne("Vaper_Api.Models.Cotizacion", "Cotizacion")
                        .WithMany("DetalleCotizaciones")
                        .HasForeignKey("CotizacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Detalle_C__Cotiz");

                    b.HasOne("Vaper_Api.Models.Producto", "Producto")
                        .WithMany("DetalleCotizaciones")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Detalle_C__Produ");

                    b.Navigation("Cotizacion");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Vaper_Api.Models.DetalleDevolucione", b =>
                {
                    b.HasOne("Vaper_Api.Models.Devolucione", "Devolucion")
                        .WithMany("DetalleDevoluciones")
                        .HasForeignKey("DevolucionId")
                        .HasConstraintName("FK__Detalle_D__Devol__208CD6FA");

                    b.HasOne("Vaper_Api.Models.Usuario", "Usuario")
                        .WithMany("DetalleDevoluciones")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__Detalle_D__Usuar__22751F6C");

                    b.HasOne("Vaper_Api.Models.DetalleVentaPedido", "VentaPedido")
                        .WithMany("DetalleDevoluciones")
                        .HasForeignKey("VentaPedidoId")
                        .HasConstraintName("FK__Detalle_D__Venta__2180FB33");

                    b.Navigation("Devolucion");

                    b.Navigation("Usuario");

                    b.Navigation("VentaPedido");
                });

            modelBuilder.Entity("Vaper_Api.Models.DetalleVentaPedido", b =>
                {
                    b.HasOne("Vaper_Api.Models.Producto", "Producto")
                        .WithMany("DetalleVentaPedidos")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("FK__Detalle_V__Produ__08B54D69");

                    b.HasOne("Vaper_Api.Models.VentaPedido", "VentaPedido")
                        .WithMany("DetalleVentaPedidos")
                        .HasForeignKey("VentaPedidoId")
                        .HasConstraintName("FK__Detalle_V__Venta__07C12930");

                    b.Navigation("Producto");

                    b.Navigation("VentaPedido");
                });

            modelBuilder.Entity("Vaper_Api.Models.Imagene", b =>
                {
                    b.HasOne("Vaper_Api.Models.Producto", "Producto")
                        .WithMany("Imagenes")
                        .HasForeignKey("ProductoId")
                        .HasConstraintName("FK__Imagenes__Produc__7F2BE32F");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Vaper_Api.Models.Producto", b =>
                {
                    b.HasOne("Vaper_Api.Models.CategoriaProducto", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .HasConstraintName("FK__Productos__Categ__7D439ABD");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Vaper_Api.Models.RolesPermiso", b =>
                {
                    b.HasOne("Vaper_Api.Models.Permiso", "Permiso")
                        .WithMany("RolesPermisos")
                        .HasForeignKey("PermisoId")
                        .HasConstraintName("FK__Roles_Per__Permi__71D1E811");

                    b.HasOne("Vaper_Api.Models.Role", "Rol")
                        .WithMany("RolesPermisos")
                        .HasForeignKey("RolId")
                        .HasConstraintName("FK__Roles_Per__RolId__70DDC3D8");

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Vaper_Api.Models.Usuario", b =>
                {
                    b.HasOne("Vaper_Api.Models.Role", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .HasConstraintName("FK__Usuarios__RolId__74AE54BC");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Vaper_Api.Models.VentaPedido", b =>
                {
                    b.HasOne("Vaper_Api.Models.Estado", "Estado")
                        .WithMany("VentaPedidos")
                        .HasForeignKey("EstadoId")
                        .HasConstraintName("FK__Venta_Ped__Estad__04E4BC85");

                    b.HasOne("Vaper_Api.Models.Usuario", "Usuario")
                        .WithMany("VentaPedidos")
                        .HasForeignKey("UsuarioId")
                        .HasConstraintName("FK__Venta_Ped__Usuar__03F0984C");

                    b.Navigation("Estado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Vaper_Api.Models.CategoriaProducto", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Vaper_Api.Models.Compra", b =>
                {
                    b.Navigation("DetalleCompras");
                });

            modelBuilder.Entity("Vaper_Api.Models.Cotizacion", b =>
                {
                    b.Navigation("DetalleCotizaciones");
                });

            modelBuilder.Entity("Vaper_Api.Models.DetalleVentaPedido", b =>
                {
                    b.Navigation("DetalleDevoluciones");
                });

            modelBuilder.Entity("Vaper_Api.Models.Devolucione", b =>
                {
                    b.Navigation("DetalleDevoluciones");
                });

            modelBuilder.Entity("Vaper_Api.Models.Estado", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("VentaPedidos");
                });

            modelBuilder.Entity("Vaper_Api.Models.Imagene", b =>
                {
                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("Vaper_Api.Models.Permiso", b =>
                {
                    b.Navigation("RolesPermisos");
                });

            modelBuilder.Entity("Vaper_Api.Models.Producto", b =>
                {
                    b.Navigation("DetalleCompras");

                    b.Navigation("DetalleCotizaciones");

                    b.Navigation("DetalleVentaPedidos");

                    b.Navigation("Imagenes");
                });

            modelBuilder.Entity("Vaper_Api.Models.Proveedore", b =>
                {
                    b.Navigation("Compras");
                });

            modelBuilder.Entity("Vaper_Api.Models.Role", b =>
                {
                    b.Navigation("RolesPermisos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Vaper_Api.Models.Usuario", b =>
                {
                    b.Navigation("DetalleDevoluciones");

                    b.Navigation("VentaPedidos");
                });

            modelBuilder.Entity("Vaper_Api.Models.VentaPedido", b =>
                {
                    b.Navigation("Abonos");

                    b.Navigation("DetalleVentaPedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
